import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./Providers";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nixa TaeKwon-Do Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/img/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="mt-[50px]">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
