import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./Providers";
import Header from "@/components/Header";
import { AuthProvider } from "../context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nixa TaeKwon-Do Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/img/favicon.ico" />
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <Providers>
            <Header />
            <div className="pt-[50px] bg-light dark:bg-dark min-h-full">
              {children}
            </div>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
