import "./globals.css";
import { Inter } from "next/font/google";

// COMPONENTS
import Providers from "./Providers";
import Header from "@/components/Header";
import Logo from "@/components/Logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nixa TKD Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Logo />
          <Header />
          {/* SEARCH */}

          {children}
        </Providers>
      </body>
    </html>
  );
}
